packages:
  - apps/**
  - packages/**

catalog:
  '@types/node': ^25
  '@types/react': ^19
  '@types/react-dom': ^19
  react: ^19
  react-dom: ^19
  tailwindcss: ^4
  tsx: ^4
  typescript: ^5
  zod: ^4

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

nodeLinker: hoisted
